version: "3.9"
services:
  ditto:
    build:
      context: ./ditto
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./ditto:/app/ditto
    env_file:
      - .env
    environment:
      - DITTO_API_BASE_URL
      - DITTO_USERNAME
      - DITTO_PASSWORD

  ml_algorithm:
    build:
      context: ./ml_algorithm
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./ml_algorithm:/app/ml_algorithm
      - ./models/plots:/app/models/plots 
    env_file:
      - .env

  influxdb:
    image: influxdb:2.7.5
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - .env
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: metrics_bucket
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2:rw
      - influxdb2-config:/etc/influxdb2:rw

  fastapi:
    build:
      context: ./  
      dockerfile: Dockerfile  
    ports:
      - "8000:8000" 
    volumes:
      - ./:/app  
    env_file:
      - .env  
    depends_on:
      - ditto
      - ml_algorithm
      - influxdb
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

secrets:
  influxdb2-admin-username:
    file: ./influxdb/secrets/influxdb2-admin-username
  influxdb2-admin-password:
    file: ./influxdb/secrets/influxdb2-admin-password
  influxdb2-admin-token:
    file: ./influxdb/secrets/influxdb2-admin-token

volumes:
  influxdb2-data:
  influxdb2-config:
